name: Build and Deploy to EC2
 
on:
  push:
    branches:
      - dev # or any branch you want to trigger the workflow
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
 
    - name: Build Docker image
      run: |
        docker build -t myapp:latest .
 
    - name: Save Docker image to disk
      run: |
        docker save myapp:latest > myapp.tar
 
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp-image
        path: myapp.tar
 
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker if not present
          if ! command -v docker &> /dev/null
          then
              sudo apt-get update
              sudo apt-get install -y docker.io
          fi
 
          # Load the Docker image
          docker load < myapp.tar
 
          # Stop and remove existing container if running
          if [ $(docker ps -q -f name=myapp) ]; then
            docker stop myapp
            docker rm myapp
          fi
 
          # Run the Docker container
          docker run -d --name myapp -p 80:80 myapp:latest
